### ISSUE TITLE
Error when initiating a transfer (using Argent wallet) 

### ISSUE THREAD

**Issue by abonn** [Loopring/dexwebapp#157]
After successfully registering a Loopring account using Argent I loaded my account with some ETH. I also traded some ETH to LRC successfully. 

However, I am unable to make transfers to other Loopring users (I've tried both ETH and LRC). After signing the transaction in Argent the following error shows up on Loopring's interface: "Your transfer request is failed, please try again" 

I'm using Brave browser, Windows 10. Argent is being used on an Android phone (version 8.0.0) 

Note: Both Loopring accounts (sender & receiver) have been active for more than 24 hours.

**Comment by xiaowheat** [comment]
Fixed in d40b20942f6033b734f027f7fd8118683dd178f1

**Comment by abonn** [comment]
I still receive an error when trying to make a transfer after signing for the transaction. There are other users in Discord reporting the same error using Argent and Wallet Connect.

**Comment by ebirbe** [comment]
@xiaowheat I can confirm this issue it's still presesnt. I've got the same result as @abonn when testing an Argent account. And there is some more info about the request results:

![Selección_999(036)](https://user-images.githubusercontent.com/442938/84463385-9f139800-ac3f-11ea-8856-05ba884453fb.png)
![Selección_999(032)](https://user-images.githubusercontent.com/442938/84464030-696fae80-ac41-11ea-83c1-a939fdbf61d7.png)
![Selección_999(035)](https://user-images.githubusercontent.com/442938/84464047-712f5300-ac41-11ea-82c1-733e3e3bf3a8.png)

Hope it helps to find the bug.

**Comment by ebirbe** [comment]
What do you think about reopen this issue @xiaowheat ?

**Comment by xiaowheat** [comment]
@ebirbe @abonn Could you provide more information? Does it only happen to Loopring Pay or to deposit and withdraws as well?

**Comment by ebirbe** [comment]
Only at Loopring Pay @xiaowheat

**Comment by xiaowheat** [comment]
If it's lated to Loopring Pay, please clear caches in the browser.

**Comment by ebirbe** [comment]
> If it's only to Loopring Pay, please clear caches in the browser.

No, it doesn't work... I tried also Private Browsing in Chrome and Firefox and still cannot make a successful transfer. I collected this additional data from my last tries:

## **On Chrome (private browsing):**

![Selección_999(043)](https://user-images.githubusercontent.com/442938/84582353-e709fa80-adb8-11ea-8547-66095173b2c3.png)
![Selección_999(044)](https://user-images.githubusercontent.com/442938/84582359-fa1cca80-adb8-11ea-82e0-3e0290d1580a.png)
![Selección_999(045)](https://user-images.githubusercontent.com/442938/84582360-00ab4200-adb9-11ea-8c76-2563c88b0758.png)
![Selección_999(046)](https://user-images.githubusercontent.com/442938/84582364-0a34aa00-adb9-11ea-81c4-23e812bdddcb.png)

## **On Firefox (clean session):**

![Selección_999(050)](https://user-images.githubusercontent.com/442938/84582451-24bb5300-adba-11ea-8524-b27a55e5d56e.png)
![Selección_999(048)](https://user-images.githubusercontent.com/442938/84582453-284eda00-adba-11ea-9988-2a4413359149.png)
![Selección_999(049)](https://user-images.githubusercontent.com/442938/84582456-2b49ca80-adba-11ea-917a-a388a6d84a45.png)
 
Please, tell me if there is other information that could be useful for you to have a better idea of what could be happening.

**Comment by abonn** [comment]
@xiaowheat for me the error occurs after signing the transaction to transfer to another Loopring user. I was able to make deposits successfully.

**Comment by ebirbe** [comment]
> @xiaowheat for me the error occurs after signing the transaction to transfer to another Loopring user. I was able to make deposits successfully.

Me too, all these screenshots happened just after signing the transfer transaction. I was able to register, deposit and to receive transfers, but unable to transfer from the Argent's account to others.

**Comment by xiaowheat** [comment]
Please check the version of Argent app. This is a problem from an old version of theirs.
