### ISSUE TITLE
Failed to unlock your account on layer-2. Please try again.

### ISSUE THREAD

**Issue by bob3443** [Loopring/dexwebapp#226]
I keep getting this error when I try to unlock my account: "Failed to unlock your account on layer-2. Please try again." I tried resetting the layer 2 key pair, but I get a another error when I do so: "Something went wrong. Please try again!" Note that I am able to sign the prompts from Loopring in Metamask, but I get the error from the Loopring website right after signing them. It's impossible for me to access my account. I created it a few days ago, but now I can't access my funds that I deposited on Layer 2. 

![Screen Shot 2021-02-19 at 1 43 20 PM](https://user-images.githubusercontent.com/79335870/108559496-a2741e80-72b8-11eb-898a-1a26bfef27f2.png)
![Screen Shot 2021-02-19 at 1 43 35 PM](https://user-images.githubusercontent.com/79335870/108559497-a30cb500-72b8-11eb-99b2-d2d2eb3a6b4f.png)

**Comment by xiaowheat** [comment]
are you using Chrome?

**Comment by bob3443** [comment]
yes

**Comment by xiaowheat** [comment]
@bob3443 Could you share the browser console log?

Instructions to get console log:
![Screen_Shot_2021-02-20_at_11 37 32_AM](https://user-images.githubusercontent.com/18495858/108608019-d9116e00-7378-11eb-916f-d6df988da556.png)
![Screen_Shot_2021-02-20_at_11 37 38_AM](https://user-images.githubusercontent.com/18495858/108608022-db73c800-7378-11eb-93aa-8164e20f918e.png)

**Comment by bob3443** [comment]
![Screen Shot 2](https://user-images.githubusercontent.com/79335870/108608437-1deed200-7384-11eb-9726-ed6c1a091a64.png)
![Screen Shot 1](https://user-images.githubusercontent.com/79335870/108608441-1fb89580-7384-11eb-816f-3d2f3c25a213.png)

**Comment by xiaowheat** [comment]
No error message when "you sign the prompts from Loopring in Metamask, but I get the error from the Loopring website right after signing them"?

**Comment by bob3443** [comment]
correct. what i meant is that i get the error not in metamask, but on loopring if that makes sense

**Comment by xiaowheat** [comment]
Is there any error in the browser console log when you see "Something went wrong. Please try again!" ?

**Comment by bob3443** [comment]
yes. this. 

![Screen Shot 3](https://user-images.githubusercontent.com/79335870/108608924-7d021600-7387-11eb-8257-750811e31514.png)

**Comment by xiaowheat** [comment]
@bob3443  Thanks. ```TypeError: n.props.fetchInfo``` is fixed now. Could you try?

**Comment by bob3443** [comment]
hey, it still does not work, for both unlocking or resetting the layer 2 keypair. it says something about balance 0 is not enough in the console. "Error: balance of 0 is not enough."    what does this mean?

**Comment by xiaowheat** [comment]
When resetting  the layer 2 keypair, does your layer 1 have any ETH to cover the transaction fee?

Could you provide the screenshot of the browser console log for "Error: balance of 0 is not enough."?

**Comment by bob3443** [comment]
the metamask wallet has eth to cover that transaction, but i don't know if the layer 1 in Loopring has a balance, maybe not. how would i go about fixing this?

**Comment by bob3443** [comment]
my understanding is there may not be eth in my account on layer 1, but i can't unlock or reset the key pair to add eth in the account on layer 1...

**Comment by bob3443** [comment]
ok i was able to reset the keypair after depositting eth to my layer 2 from layer 1. thanks!
